version: "3"

dotenv: ['.env']  # Enable loading variables from a .env file

tasks:

  build:
    desc: "Build the Debian image"
    cmds:
      - docker build --build-arg PASSWORD=$user_password --build-arg USERNAME=$user_name -f ./debian -t debian .
      - docker run --privileged -it -e DISPLAY=$DISPLAY -v "//var/run/docker.sock:/var/run/docker.sock" -p 8080:80 --name debian-container debian /bin/bash
      # docker run -privileged -t -i jpetazzo/dind

  remove:
    desc: "Remove Debian image and containers"
    cmds:
      - docker stop debian-container || true
      - docker remove debian-container || true
      - docker rmi $(docker images -qf "reference=debian") || true

  run:
    desc: "Start the Debian container"
    cmds:
      - docker start debian-container
      - docker exec -it debian-container bash
      # - docker remove debian-container
      # - docker run -it --name debian-container debian /bin/bash

  full:
    desc: "Delete, Rebuild, and Start the Debian container"
    cmds:
      - task: remove
      - task: build
