version: "3"

dotenv: ['.env']  # Enable loading variables from a .env file

vars:
  databaseName: "yuppyword"
  hostName: "localhost"
  sqlLogin: "postgres"
  connection: "-h {{.hostName}} -U {{.sqlLogin}}"
  dbConnection: "{{.connection}} -d {{.databaseName}}"
  sqlUser: "henry.crans@gmail.com"
  sqlPass: "{{.USER_PASSWORD}}"

tasks:

  startDocker:
    desc: "Start the docker engine"
    status:
      - |
        docker info
    cmds:
      - exec "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe"

  build:
    desc: "Build the Debian image"
    cmds:
      - cp ../beautifulLetdown/.env.local apiEnv.local
      - docker build --build-arg PASSWORD=$user_password --build-arg USERNAME=$user_name --build-arg SSH="$ssh_cert" -f ./debian -t debian .
      - rm apiEnv.local
      - docker network create dareyoutomove
      - docker run --name {{.databaseName}}-container -e POSTGRES_PASSWORD=$user_password -p 5432:5432 --network dareyoutomove -d postgres 
      - docker run --privileged -it -e DISPLAY=$DISPLAY -v "//var/run/docker.sock:/var/run/docker.sock" -p 8000:8000 -p 3009:3009 --network dareyoutomove --name debian-container debian /bin/bash

  buildSqlServer:
    desc: "Build the sql server image"
    cmds:
      - |
        docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD={{.sqlPass}}" \
          -p 1433:1433 --name sqlserver \
          -d mcr.microsoft.com/mssql/server:2022-latest

  runSqlServer:
    desc: "Run the sql server container"
    cmds:
      - task startDocker
      - docker start sqlserver

  buildDb:
    desc: "Build the Debian image"
    cmds:
      - docker run --name {{.databaseName}}-container -e POSTGRES_PASSWORD=$user_password -p 5432:5432 -d postgres 

  remove:
    desc: "Remove Debian image and containers"
    cmds:
      - docker stop debian-container || true
      - docker stop {{.databaseName}}-container || true
      - docker remove debian-container || true
      - docker remove {{.databaseName}}-container || true
      - docker rmi $(docker images -qf "reference=debian") || true
      - docker rmi $(docker images -qf "reference={{.databaseName}}") || true
      - docker network remove dareyoutomove || true

  run:
    desc: "Start the Debian container"
    cmds:
      - task startDocker
      - docker start {{.databaseName}}-container

  full:
    desc: "Delete, Rebuild, and Start the Debian container"
    cmds:
      - task: remove
      - task: buildDb
